### ISSUE TITLE
How to handle "conversationData" on the skill

### ISSUE THREAD

**Issue by ssosas** [linto-ai/linto-web-client#2]
Hi all,

Could you explain quickly how do you do to handle the "conversationData" object after clicking on the button? I mean, in the skill side on the stack, how I can obtain theses values returned by the client in this object (JSON)?

May you give me an example or redirect me to an existing skill in the repo?

Many thanks!

Sergio

**Comment by damienlaine** [comment]
@ssosas : transferred issue.

**Comment by damienlaine** [comment]
answered by @yhoupert
